/* Generated by Yosys 0.44+9 (git sha1 4b9f45273, g++ 11.4.0-1ubuntu1~22.04 -fPIC -fPIC -O3) */

module top(clk, rst, x, enable, din, spike);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire \blocco3.m1.soglia[0] ;
  wire \blocco3.m1.soglia[10] ;
  wire \blocco3.m1.soglia[11] ;
  wire \blocco3.m1.soglia[1] ;
  wire \blocco3.m1.soglia[2] ;
  wire \blocco3.m1.soglia[3] ;
  wire \blocco3.m1.soglia[4] ;
  wire \blocco3.m1.soglia[5] ;
  wire \blocco3.m1.soglia[6] ;
  wire \blocco3.m1.soglia[7] ;
  wire \blocco3.m1.soglia[8] ;
  wire \blocco3.m1.soglia[9] ;
  wire \blocco3.m2.q[0] ;
  wire \blocco3.m2.q[10] ;
  wire \blocco3.m2.q[11] ;
  wire \blocco3.m2.q[1] ;
  wire \blocco3.m2.q[2] ;
  wire \blocco3.m2.q[3] ;
  wire \blocco3.m2.q[4] ;
  wire \blocco3.m2.q[5] ;
  wire \blocco3.m2.q[6] ;
  wire \blocco3.m2.q[7] ;
  wire \blocco3.m2.q[8] ;
  wire \blocco3.m2.q[9] ;
  wire \blocco3.m2.stato_corrente[0] ;
  wire \blocco3.m2.stato_corrente[1] ;
  wire \blocco3.m2.stato_corrente[2] ;
  input clk;
  wire clk;
  input din;
  wire din;
  input enable;
  wire enable;
  wire \output_iir[0] ;
  wire \output_iir[10] ;
  wire \output_iir[1] ;
  wire \output_iir[2] ;
  wire \output_iir[3] ;
  wire \output_iir[4] ;
  wire \output_iir[5] ;
  wire \output_iir[6] ;
  wire \output_iir[7] ;
  wire \output_iir[8] ;
  wire \output_iir[9] ;
  input rst;
  wire rst;
  output spike;
  wire spike;
  input [10:0] x;
  wire [10:0] x;
  INV_X1 _159_ (
    .A(\blocco3.m2.stato_corrente[0] ),
    .ZN(_094_)
  );
  NAND2_X1 _160_ (
    .A1(_094_),
    .A2(\blocco3.m2.stato_corrente[2] ),
    .ZN(_095_)
  );
  NOR2_X1 _161_ (
    .A1(_095_),
    .A2(\blocco3.m2.stato_corrente[1] ),
    .ZN(spike)
  );
  INV_X1 _162_ (
    .A(\blocco3.m2.q[7] ),
    .ZN(_096_)
  );
  NAND2_X1 _163_ (
    .A1(_096_),
    .A2(\blocco3.m1.soglia[7] ),
    .ZN(_097_)
  );
  INV_X1 _164_ (
    .A(\blocco3.m2.q[6] ),
    .ZN(_098_)
  );
  NAND2_X1 _165_ (
    .A1(_098_),
    .A2(\blocco3.m1.soglia[6] ),
    .ZN(_099_)
  );
  NAND2_X1 _166_ (
    .A1(_097_),
    .A2(_099_),
    .ZN(_100_)
  );
  INV_X1 _167_ (
    .A(\blocco3.m1.soglia[7] ),
    .ZN(_101_)
  );
  NAND2_X2 _168_ (
    .A1(_101_),
    .A2(\blocco3.m2.q[7] ),
    .ZN(_102_)
  );
  INV_X1 _169_ (
    .A(\blocco3.m1.soglia[6] ),
    .ZN(_103_)
  );
  NAND2_X1 _170_ (
    .A1(_103_),
    .A2(\blocco3.m2.q[6] ),
    .ZN(_104_)
  );
  NAND2_X2 _171_ (
    .A1(_102_),
    .A2(_104_),
    .ZN(_105_)
  );
  NOR2_X4 _172_ (
    .A1(_100_),
    .A2(_105_),
    .ZN(_106_)
  );
  INV_X2 _173_ (
    .A(\blocco3.m1.soglia[4] ),
    .ZN(_107_)
  );
  NOR2_X1 _174_ (
    .A1(_107_),
    .A2(\blocco3.m2.q[4] ),
    .ZN(_108_)
  );
  INV_X2 _175_ (
    .A(\blocco3.m1.soglia[5] ),
    .ZN(_109_)
  );
  NAND2_X1 _176_ (
    .A1(_109_),
    .A2(\blocco3.m2.q[5] ),
    .ZN(_110_)
  );
  NAND2_X1 _177_ (
    .A1(_108_),
    .A2(_110_),
    .ZN(_111_)
  );
  OR2_X1 _178_ (
    .A1(_109_),
    .A2(\blocco3.m2.q[5] ),
    .ZN(_112_)
  );
  NAND2_X1 _179_ (
    .A1(_111_),
    .A2(_112_),
    .ZN(_113_)
  );
  NAND2_X1 _180_ (
    .A1(_106_),
    .A2(_113_),
    .ZN(_114_)
  );
  NAND2_X1 _181_ (
    .A1(_100_),
    .A2(_102_),
    .ZN(_115_)
  );
  NAND2_X1 _182_ (
    .A1(_114_),
    .A2(_115_),
    .ZN(_116_)
  );
  INV_X1 _183_ (
    .A(\blocco3.m2.q[11] ),
    .ZN(_117_)
  );
  NAND2_X1 _184_ (
    .A1(_117_),
    .A2(\blocco3.m1.soglia[11] ),
    .ZN(_118_)
  );
  INV_X1 _185_ (
    .A(\blocco3.m1.soglia[11] ),
    .ZN(_119_)
  );
  NAND2_X1 _186_ (
    .A1(_119_),
    .A2(\blocco3.m2.q[11] ),
    .ZN(_120_)
  );
  NAND2_X1 _187_ (
    .A1(_118_),
    .A2(_120_),
    .ZN(_121_)
  );
  INV_X1 _188_ (
    .A(\blocco3.m2.q[10] ),
    .ZN(_122_)
  );
  NAND2_X1 _189_ (
    .A1(_122_),
    .A2(\blocco3.m1.soglia[10] ),
    .ZN(_123_)
  );
  INV_X1 _190_ (
    .A(\blocco3.m1.soglia[10] ),
    .ZN(_124_)
  );
  NAND2_X1 _191_ (
    .A1(_124_),
    .A2(\blocco3.m2.q[10] ),
    .ZN(_125_)
  );
  NAND2_X1 _192_ (
    .A1(_123_),
    .A2(_125_),
    .ZN(_126_)
  );
  NOR2_X4 _193_ (
    .A1(_121_),
    .A2(_126_),
    .ZN(_127_)
  );
  INV_X1 _194_ (
    .A(\blocco3.m2.q[8] ),
    .ZN(_128_)
  );
  NAND2_X1 _195_ (
    .A1(_128_),
    .A2(\blocco3.m1.soglia[8] ),
    .ZN(_129_)
  );
  INV_X1 _196_ (
    .A(\blocco3.m1.soglia[8] ),
    .ZN(_130_)
  );
  NAND2_X1 _197_ (
    .A1(_130_),
    .A2(\blocco3.m2.q[8] ),
    .ZN(_131_)
  );
  NAND2_X1 _198_ (
    .A1(_129_),
    .A2(_131_),
    .ZN(_132_)
  );
  INV_X1 _199_ (
    .A(\blocco3.m1.soglia[9] ),
    .ZN(_133_)
  );
  NAND2_X2 _200_ (
    .A1(_133_),
    .A2(\blocco3.m2.q[9] ),
    .ZN(_134_)
  );
  INV_X1 _201_ (
    .A(\blocco3.m2.q[9] ),
    .ZN(_135_)
  );
  NAND2_X1 _202_ (
    .A1(_135_),
    .A2(\blocco3.m1.soglia[9] ),
    .ZN(_136_)
  );
  NAND2_X2 _203_ (
    .A1(_134_),
    .A2(_136_),
    .ZN(_137_)
  );
  NOR2_X2 _204_ (
    .A1(_132_),
    .A2(_137_),
    .ZN(_138_)
  );
  NAND2_X4 _205_ (
    .A1(_127_),
    .A2(_138_),
    .ZN(_139_)
  );
  INV_X2 _206_ (
    .A(_139_),
    .ZN(_140_)
  );
  NAND2_X1 _207_ (
    .A1(_116_),
    .A2(_140_),
    .ZN(_141_)
  );
  INV_X1 _208_ (
    .A(_120_),
    .ZN(_142_)
  );
  OAI21_X1 _209_ (
    .A(_118_),
    .B1(_142_),
    .B2(_123_),
    .ZN(_143_)
  );
  INV_X1 _210_ (
    .A(_134_),
    .ZN(_144_)
  );
  OAI21_X1 _211_ (
    .A(_136_),
    .B1(_144_),
    .B2(_129_),
    .ZN(_016_)
  );
  AOI21_X1 _212_ (
    .A(_143_),
    .B1(_127_),
    .B2(_016_),
    .ZN(_017_)
  );
  NAND2_X1 _213_ (
    .A1(_141_),
    .A2(_017_),
    .ZN(_018_)
  );
  INV_X2 _214_ (
    .A(_018_),
    .ZN(_019_)
  );
  INV_X1 _215_ (
    .A(_121_),
    .ZN(_020_)
  );
  INV_X1 _216_ (
    .A(\blocco3.m2.q[1] ),
    .ZN(_021_)
  );
  NAND2_X1 _217_ (
    .A1(_021_),
    .A2(\blocco3.m1.soglia[1] ),
    .ZN(_022_)
  );
  INV_X1 _218_ (
    .A(\blocco3.m1.soglia[1] ),
    .ZN(_023_)
  );
  NAND2_X1 _219_ (
    .A1(_023_),
    .A2(\blocco3.m2.q[1] ),
    .ZN(_024_)
  );
  NAND2_X1 _220_ (
    .A1(_022_),
    .A2(_024_),
    .ZN(_025_)
  );
  INV_X1 _221_ (
    .A(\blocco3.m1.soglia[0] ),
    .ZN(_026_)
  );
  AND2_X1 _222_ (
    .A1(_026_),
    .A2(\blocco3.m2.q[0] ),
    .ZN(_027_)
  );
  OAI21_X1 _223_ (
    .A(_022_),
    .B1(_025_),
    .B2(_027_),
    .ZN(_028_)
  );
  INV_X1 _224_ (
    .A(\blocco3.m2.q[3] ),
    .ZN(_029_)
  );
  NAND2_X1 _225_ (
    .A1(_029_),
    .A2(\blocco3.m1.soglia[3] ),
    .ZN(_030_)
  );
  INV_X1 _226_ (
    .A(\blocco3.m2.q[2] ),
    .ZN(_031_)
  );
  NAND2_X1 _227_ (
    .A1(_031_),
    .A2(\blocco3.m1.soglia[2] ),
    .ZN(_032_)
  );
  NAND2_X1 _228_ (
    .A1(_030_),
    .A2(_032_),
    .ZN(_033_)
  );
  INV_X1 _229_ (
    .A(\blocco3.m1.soglia[3] ),
    .ZN(_034_)
  );
  NAND2_X1 _230_ (
    .A1(_034_),
    .A2(\blocco3.m2.q[3] ),
    .ZN(_035_)
  );
  INV_X1 _231_ (
    .A(\blocco3.m1.soglia[2] ),
    .ZN(_036_)
  );
  NAND2_X1 _232_ (
    .A1(_036_),
    .A2(\blocco3.m2.q[2] ),
    .ZN(_037_)
  );
  NAND2_X1 _233_ (
    .A1(_035_),
    .A2(_037_),
    .ZN(_038_)
  );
  NOR2_X2 _234_ (
    .A1(_033_),
    .A2(_038_),
    .ZN(_039_)
  );
  NAND2_X1 _235_ (
    .A1(_028_),
    .A2(_039_),
    .ZN(_040_)
  );
  NAND2_X1 _236_ (
    .A1(_033_),
    .A2(_035_),
    .ZN(_041_)
  );
  NAND2_X1 _237_ (
    .A1(_040_),
    .A2(_041_),
    .ZN(_042_)
  );
  XNOR2_X1 _238_ (
    .A(_109_),
    .B(\blocco3.m2.q[5] ),
    .ZN(_043_)
  );
  XNOR2_X2 _239_ (
    .A(_107_),
    .B(\blocco3.m2.q[4] ),
    .ZN(_044_)
  );
  NOR2_X4 _240_ (
    .A1(_043_),
    .A2(_044_),
    .ZN(_045_)
  );
  NAND2_X4 _241_ (
    .A1(_045_),
    .A2(_106_),
    .ZN(_046_)
  );
  NOR2_X4 _242_ (
    .A1(_046_),
    .A2(_139_),
    .ZN(_047_)
  );
  NAND2_X2 _243_ (
    .A1(_042_),
    .A2(_047_),
    .ZN(_048_)
  );
  NAND3_X4 _244_ (
    .A1(_019_),
    .A2(_020_),
    .A3(_048_),
    .ZN(_049_)
  );
  NOR2_X1 _245_ (
    .A1(_026_),
    .A2(\blocco3.m2.q[0] ),
    .ZN(_050_)
  );
  NOR3_X1 _246_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_050_),
    .ZN(_051_)
  );
  NAND3_X2 _247_ (
    .A1(_047_),
    .A2(_039_),
    .A3(_051_),
    .ZN(_052_)
  );
  NAND2_X1 _248_ (
    .A1(_052_),
    .A2(_118_),
    .ZN(_053_)
  );
  INV_X2 _249_ (
    .A(_053_),
    .ZN(_054_)
  );
  NAND2_X4 _250_ (
    .A1(_049_),
    .A2(_054_),
    .ZN(_055_)
  );
  NAND2_X2 _251_ (
    .A1(_055_),
    .A2(_094_),
    .ZN(_056_)
  );
  NAND2_X1 _252_ (
    .A1(_000_),
    .A2(\blocco3.m2.stato_corrente[1] ),
    .ZN(_057_)
  );
  INV_X1 _253_ (
    .A(_057_),
    .ZN(_058_)
  );
  NAND2_X2 _254_ (
    .A1(_056_),
    .A2(_058_),
    .ZN(_059_)
  );
  NAND2_X2 _255_ (
    .A1(_055_),
    .A2(_095_),
    .ZN(_060_)
  );
  NOR2_X1 _256_ (
    .A1(_094_),
    .A2(\blocco3.m2.stato_corrente[1] ),
    .ZN(_061_)
  );
  NAND2_X1 _257_ (
    .A1(_061_),
    .A2(_000_),
    .ZN(_062_)
  );
  INV_X1 _258_ (
    .A(_062_),
    .ZN(_063_)
  );
  NAND2_X1 _259_ (
    .A1(_061_),
    .A2(\blocco3.m2.stato_corrente[2] ),
    .ZN(_064_)
  );
  INV_X1 _260_ (
    .A(_064_),
    .ZN(_065_)
  );
  NOR2_X1 _261_ (
    .A1(_063_),
    .A2(_065_),
    .ZN(_066_)
  );
  NAND3_X1 _262_ (
    .A1(_049_),
    .A2(_054_),
    .A3(_066_),
    .ZN(_067_)
  );
  NAND2_X1 _263_ (
    .A1(_060_),
    .A2(_067_),
    .ZN(_068_)
  );
  AOI21_X2 _264_ (
    .A(rst),
    .B1(_059_),
    .B2(_068_),
    .ZN(_015_)
  );
  NAND2_X4 _265_ (
    .A1(_055_),
    .A2(_063_),
    .ZN(_069_)
  );
  NAND3_X1 _266_ (
    .A1(_049_),
    .A2(_054_),
    .A3(_065_),
    .ZN(_070_)
  );
  NAND3_X1 _267_ (
    .A1(_094_),
    .A2(_000_),
    .A3(\blocco3.m2.stato_corrente[1] ),
    .ZN(_071_)
  );
  NAND3_X2 _268_ (
    .A1(_069_),
    .A2(_070_),
    .A3(_071_),
    .ZN(_072_)
  );
  INV_X1 _269_ (
    .A(rst),
    .ZN(_073_)
  );
  BUF_X4 _270_ (
    .A(_073_),
    .Z(_074_)
  );
  NAND2_X2 _271_ (
    .A1(_072_),
    .A2(_074_),
    .ZN(_075_)
  );
  INV_X2 _272_ (
    .A(_075_),
    .ZN(_014_)
  );
  NAND2_X1 _273_ (
    .A1(_074_),
    .A2(_000_),
    .ZN(_076_)
  );
  NAND3_X1 _274_ (
    .A1(_049_),
    .A2(_054_),
    .A3(_061_),
    .ZN(_077_)
  );
  AOI21_X2 _275_ (
    .A(_076_),
    .B1(_056_),
    .B2(_077_),
    .ZN(_013_)
  );
  BUF_X1 _276_ (
    .A(enable),
    .Z(_078_)
  );
  OAI21_X1 _277_ (
    .A(_074_),
    .B1(\blocco3.m1.soglia[9] ),
    .B2(_078_),
    .ZN(_079_)
  );
  BUF_X1 _278_ (
    .A(_078_),
    .Z(_080_)
  );
  AOI21_X1 _279_ (
    .A(_079_),
    .B1(_130_),
    .B2(_080_),
    .ZN(_012_)
  );
  OAI21_X1 _280_ (
    .A(_074_),
    .B1(\blocco3.m1.soglia[8] ),
    .B2(_078_),
    .ZN(_081_)
  );
  BUF_X1 _281_ (
    .A(_078_),
    .Z(_082_)
  );
  AOI21_X1 _282_ (
    .A(_081_),
    .B1(_082_),
    .B2(_101_),
    .ZN(_011_)
  );
  OAI21_X1 _283_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[7] ),
    .ZN(_083_)
  );
  AOI21_X1 _284_ (
    .A(_083_),
    .B1(_082_),
    .B2(_103_),
    .ZN(_010_)
  );
  OAI21_X1 _285_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[6] ),
    .ZN(_084_)
  );
  AOI21_X1 _286_ (
    .A(_084_),
    .B1(_082_),
    .B2(_109_),
    .ZN(_009_)
  );
  OAI21_X1 _287_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[5] ),
    .ZN(_085_)
  );
  AOI21_X1 _288_ (
    .A(_085_),
    .B1(_082_),
    .B2(_107_),
    .ZN(_008_)
  );
  OAI21_X1 _289_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[4] ),
    .ZN(_086_)
  );
  AOI21_X1 _290_ (
    .A(_086_),
    .B1(_082_),
    .B2(_034_),
    .ZN(_007_)
  );
  OAI21_X1 _291_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[3] ),
    .ZN(_087_)
  );
  AOI21_X1 _292_ (
    .A(_087_),
    .B1(_082_),
    .B2(_036_),
    .ZN(_006_)
  );
  OAI21_X1 _293_ (
    .A(_074_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[2] ),
    .ZN(_088_)
  );
  AOI21_X1 _294_ (
    .A(_088_),
    .B1(_082_),
    .B2(_023_),
    .ZN(_005_)
  );
  OAI21_X1 _295_ (
    .A(_073_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[1] ),
    .ZN(_089_)
  );
  AOI21_X1 _296_ (
    .A(_089_),
    .B1(_082_),
    .B2(_026_),
    .ZN(_004_)
  );
  OAI21_X1 _297_ (
    .A(_073_),
    .B1(_080_),
    .B2(\blocco3.m1.soglia[11] ),
    .ZN(_090_)
  );
  AOI21_X1 _298_ (
    .A(_090_),
    .B1(_082_),
    .B2(_124_),
    .ZN(_003_)
  );
  OAI21_X1 _299_ (
    .A(_073_),
    .B1(_078_),
    .B2(\blocco3.m1.soglia[10] ),
    .ZN(_091_)
  );
  AOI21_X1 _300_ (
    .A(_091_),
    .B1(_133_),
    .B2(_080_),
    .ZN(_002_)
  );
  OAI21_X1 _301_ (
    .A(_073_),
    .B1(_078_),
    .B2(\blocco3.m1.soglia[0] ),
    .ZN(_092_)
  );
  INV_X1 _302_ (
    .A(din),
    .ZN(_093_)
  );
  AOI21_X1 _303_ (
    .A(_092_),
    .B1(_082_),
    .B2(_093_),
    .ZN(_001_)
  );
  iir blocco1 (
    .clk(clk),
    .rst(rst),
    .x(x),
    .z({ \output_iir[10] , \output_iir[9] , \output_iir[8] , \output_iir[7] , \output_iir[6] , \output_iir[5] , \output_iir[4] , \output_iir[3] , \output_iir[2] , \output_iir[1] , \output_iir[0]  })
  );
  enfasi blocco2 (
    .clk(clk),
    .q({ \blocco3.m2.q[11] , \blocco3.m2.q[10] , \blocco3.m2.q[9] , \blocco3.m2.q[8] , \blocco3.m2.q[7] , \blocco3.m2.q[6] , \blocco3.m2.q[5] , \blocco3.m2.q[4] , \blocco3.m2.q[3] , \blocco3.m2.q[2] , \blocco3.m2.q[1] , \blocco3.m2.q[0]  }),
    .rst(rst),
    .z({ \output_iir[10] , \output_iir[9] , \output_iir[8] , \output_iir[7] , \output_iir[6] , \output_iir[5] , \output_iir[4] , \output_iir[3] , \output_iir[2] , \output_iir[1] , \output_iir[0]  })
  );
  DFF_X1 \blocco3.m1.soglia[0]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_001_),
    .Q(\blocco3.m1.soglia[0] ),
    .QN(_158_)
  );
  DFF_X1 \blocco3.m1.soglia[10]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_002_),
    .Q(\blocco3.m1.soglia[10] ),
    .QN(_157_)
  );
  DFF_X1 \blocco3.m1.soglia[11]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_003_),
    .Q(\blocco3.m1.soglia[11] ),
    .QN(_156_)
  );
  DFF_X1 \blocco3.m1.soglia[1]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_004_),
    .Q(\blocco3.m1.soglia[1] ),
    .QN(_155_)
  );
  DFF_X1 \blocco3.m1.soglia[2]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_005_),
    .Q(\blocco3.m1.soglia[2] ),
    .QN(_154_)
  );
  DFF_X1 \blocco3.m1.soglia[3]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_006_),
    .Q(\blocco3.m1.soglia[3] ),
    .QN(_153_)
  );
  DFF_X1 \blocco3.m1.soglia[4]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_007_),
    .Q(\blocco3.m1.soglia[4] ),
    .QN(_152_)
  );
  DFF_X1 \blocco3.m1.soglia[5]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_008_),
    .Q(\blocco3.m1.soglia[5] ),
    .QN(_151_)
  );
  DFF_X1 \blocco3.m1.soglia[6]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_009_),
    .Q(\blocco3.m1.soglia[6] ),
    .QN(_150_)
  );
  DFF_X1 \blocco3.m1.soglia[7]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_010_),
    .Q(\blocco3.m1.soglia[7] ),
    .QN(_149_)
  );
  DFF_X1 \blocco3.m1.soglia[8]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_011_),
    .Q(\blocco3.m1.soglia[8] ),
    .QN(_148_)
  );
  DFF_X1 \blocco3.m1.soglia[9]$_SDFFE_PP0P_  (
    .CK(clk),
    .D(_012_),
    .Q(\blocco3.m1.soglia[9] ),
    .QN(_147_)
  );
  DFF_X1 \blocco3.m2.stato_corrente[0]$_SDFF_PP0_  (
    .CK(clk),
    .D(_013_),
    .Q(\blocco3.m2.stato_corrente[0] ),
    .QN(_146_)
  );
  DFF_X1 \blocco3.m2.stato_corrente[1]$_SDFF_PP0_  (
    .CK(clk),
    .D(_014_),
    .Q(\blocco3.m2.stato_corrente[1] ),
    .QN(_145_)
  );
  DFF_X1 \blocco3.m2.stato_corrente[2]$_SDFF_PP0_  (
    .CK(clk),
    .D(_015_),
    .Q(\blocco3.m2.stato_corrente[2] ),
    .QN(_000_)
  );
endmodule
